### ISSUE TITLE
rboot-sampleproject won't compile on Windows with UDK>2.0.6

### ISSUE THREAD

**Issue by gernoteger** [raburton/esp8266#23]
When compiling with UnofficialDevelopmentKit > 2.0.6 I get:

```
CC main.c
In file included from main.c:9:0:
main.c: In function 'network_wait_for_ip':
C:/Espressif/ESP8266_SDK/include/osapi.h:31:25: error: implicit declaration of function 'ets_timer_disarm' [-Werror=implicit-function-declaration]
 #define os_timer_disarm ets_timer_disarm
                         ^
main.c:27:2: note: in expansion of macro 'os_timer_disarm'
  os_timer_disarm(&network_timer);
  ^
C:/Espressif/ESP8266_SDK/include/osapi.h:34:21: error: implicit declaration of function 'ets_sprintf' [-Werror=implicit-function-declaration]
 #define os_sprintf  ets_sprintf
                     ^
main.c:31:3: note: in expansion of macro 'os_sprintf'
   os_sprintf(page_buffer,"ip: %d.%d.%d.%d\r\n",IP2STR(&ipconfig.ip));
   ^
C:/Espressif/ESP8266_SDK/include/osapi.h:32:24: error: implicit declaration of function 'ets_timer_setfn' [-Werror=implicit-function-declaration]
 #define os_timer_setfn ets_timer_setfn
                        ^
main.c:38:3: note: in expansion of macro 'os_timer_setfn'
   os_timer_setfn(&network_timer, (os_timer_func_t *)network_wait_for_ip, NULL);
```

probable Reason:
WIth UDK 2.0.7 the gcc is moved from 4.8.2 to 5.1.0
